/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Setting = {
  [k: string]: unknown;
} & {
  /**
   * The ID of the setting.
   */
  id: string;
  /**
   * The display name for the setting.
   */
  name: string;
  /**
   * The type of UI control for this setting.
   */
  type: "text" | "slider" | "toggle";
  /**
   * The default value for the setting.
   */
  default: {
    [k: string]: unknown;
  };
  /**
   * The minimum value for the slider.
   */
  min?: number;
  /**
   * The maximum value for the slider.
   */
  max?: number;
  /**
   * The increment value for the slider.
   */
  snap?: number;
  /**
   * The prompt text for the setting.
   */
  prompt?: string;
  [k: string]: unknown;
};

/**
 * Schema for the meta.json file of a Scratch Everywhere! custom extension.
 */
export interface ScratchEverywhereCustomExtensionMetadata {
  /**
   * Indicates if the extension shoule be considered a core extension.
   */
  core: boolean;
  /**
   * The ID of the custom extension, should match the one in TurboWarp.
   */
  id: string;
  /**
   * The human-readable name of the custom extension.
   */
  name: string;
  /**
   * A brief summary of what the custom extension does.
   */
  description: string;
  /**
   * A list of permissions the custom extension requires to function.
   */
  permissions: (
    | "localfs"
    | "rootfs"
    | "network"
    | "input"
    | "render"
    | "update"
    | "platform-specific"
    | "runtime"
    | "audio"
    | "extensions"
  )[];
  /**
   * A list of platforms this custom extension is compatible with.
   */
  platforms: ("3ds" | "wiiu" | "wii" | "gamecube" | "switch" | "pc" | "vita")[];
  /**
   * The minimum required API version in 'major.minor' format.
   */
  minAPI?: string;
  /**
   * An array of user-configurable settings for the custom extension.
   */
  settings?: Setting[];
  [k: string]: unknown;
}
